# Generated by Django 2.1.4 on 2018-12-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0002_auto_20181206_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokumodel',
            name='board_title',
            field=models.CharField(default='95e20dbc-0dd', editable=False, max_length=12),
        ),
    ]
