# Generated by Django 2.1.4 on 2018-12-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0003_auto_20181206_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokumodel',
            name='board_diffic',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='sudokumodel',
            name='board_title',
            field=models.CharField(default='56d492dd-41e', max_length=12),
        ),
    ]
