# Generated by Django 2.1.4 on 2018-12-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0004_auto_20181206_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokumodel',
            name='board_title',
            field=models.CharField(editable=False, max_length=12),
        ),
    ]
