# Generated by Django 2.1.4 on 2018-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0005_auto_20181206_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokumodel',
            name='board_data',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sudokumodel',
            name='board_solution',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
