# Generated by Django 2.1.4 on 2018-12-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0006_auto_20181207_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokumodel',
            name='board_data',
            field=models.CharField(blank=True, max_length=261, null=True),
        ),
        migrations.AlterField(
            model_name='sudokumodel',
            name='board_solution',
            field=models.CharField(blank=True, max_length=261, null=True),
        ),
    ]
