# Generated by Django 2.1.4 on 2018-12-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0008_auto_20181208_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokumodel',
            name='board_data',
            field=models.CharField(blank=True, max_length=423, null=True),
        ),
    ]
